{{- if .Values.eos.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oracle-eos
spec:
  selector:
    matchLabels:
      app: oracle-eos
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
        labels:
            app: oracle-eos
    spec:
      containers:
        - name: oracle-eos
          image: {{ .Values.eos.image }}
          command: ['yarn', 'eos']
          imagePullPolicy: Always
          env:
            - name: ORACLE_NAME
              value: {{ .Release.Name }}
            - name: EOS_CONTRACT_ACCOUNT
              value: {{ .Values.eos.contractAccount }}
            - name: EOS_ORACLE_ACCOUNT
              value: {{ .Values.eos.oracleAccount  }}
            - name: EOS_API_ENDPOINT
              value: {{ .Values.eos.https }}
            - name: DFUSE_API_KEY
              value: {{ .Values.eos.dfuse.apiKey }}
            - name: DFUSE_NETWORK
              value: {{ .Values.eos.dfuse.network }}
            - name: EOS_ORACLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: eosPrivateKey
            - name: POLYGON_ORACLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: polygonPrivateKey
            - name: BSC_ORACLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: bscPrivateKey
          volumeMounts:
          - mountPath: /app
            name: token-map
      volumes:
        - name: token-map
          configMap:
            name: {{ .Release.Name }}-token-map
{{ end }}