{{- if .Values.bsc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oracle-bsc
spec:
  selector:
    matchLabels:
      app: oracle-bsc
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: oracle-bsc
    spec:
      containers:
        - name: oracle-bsc
          image: {{ .Values.common.image }}
          command: ['yarn', 'bsc']
          imagePullPolicy: Always
          env:
            - name: ORACLE_NAME
              value: {{ .Values.bsc.abiPath }}
            - name: ETH_BRIDGE_ABI_PATH
              value: {{ .Values.bsc.abiPath }}
            - name: ETH_WEBSOCKET_URI
              value: {{ .Values.bsc.websocketUri }}
            - name: ETH_CONTRACT_ADDRESS
              value: {{ .Values.bsc.contractAddress }}
            - name: EOS_API_ENDPOINT
              value: {{ .Values.eos.httpsUri }}
            - name: EOS_CONTRACT_ACCOUNT
              value: {{ .Values.eos.contractAccount }}
            - name: DFUSE_API_KEY
              value: {{ .Values.eos.dfuse.apiKey }}
            - name: DFUSE_NETWORK
              value: {{ .Values.eos.dfuse.network }}
            - name: EOS_ORACLE_ACCOUNT
              value: {{ .Values.eos.oracleAccount  }}
            - name: EOS_ORACLE_PRIVATE_KEY
              value: {{ .Values.eos.privateKey  }}
{{ end }}