apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oracle-polygon
spec:
  selector:
    matchLabels:
      app: oracle-polygon
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: oracle-polygon
    spec:
      containers:
        - name: oracle-polygon
          image: {{ .Values.eos.image }}
          command: ['yarn', 'polygon']
          imagePullPolicy: Always
          env:
            - name: ETH_HTTP_API_ENDPOINT
              value: {{ .Values.endpoints.polygon.https }}
            - name: ETH_WEBSOCKET_URI
              value: {{ .Values.endpoints.polygon.wss }}
            - name: ETH_CONTRACT_ADDRESS
              value: {{ .Values.contract.polygon }}
            - name: EOS_API_ENDPOINT
              value: {{ .Values.endpoints.eos.https }}
            - name: EOS_CONTRACT_ACCOUNT
              value: {{ .Values.contract.eos }}
            - name: DFUSE_API_KEY
              value: {{ .Values.dfuse.apiKey }}
            - name: DFUSE_NETWORK
              value: {{ .Values.dfuse.network }}
            - name: ORACLE_EOS_ACCOUNT
              value: {{ .Values.eosAccount  }}
            - name: ORACLE_EOS_PRIVATE_KEY
              value: {{ .Values.eosPrivateKey  }}
            - name: ETH_PRIVATE_KEY
              value: {{ .Values.polygonPrivateKey  }}