apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  eosPrivateKey: {{ .Values.eos.privateKey | b64enc }}
  polygonPrivateKey: {{ .Values.bsc.privateKey | b64enc }}
  bscPrivateKey: {{ .Values.polygon.privateKey | b64enc }}