module.exports = {
  reactStrictMode: true,
  env: {
    BLU_BRIDGER_CONTRACT: process.env.BLU_BRIDGER_CONTRACT,
    BLU_TOKEN_CONTRACT: process.env.BLU_TOKEN_CONTRACT,
    DFUSE_API_KEY: process.env.DFUSE_API_KEY,
    DFUSE_API_NETWORK: process.env.DFUSE_API_NETWORK,
    EOS_BLU_BRIDGER_CONTRACT: process.env.EOS_BLU_BRIDGER_CONTRACT,
    EOS_TOKEN_CONTRACT: process.env.EOS_TOKEN_CONTRACT,
    EOS_TOKEN_SYMBOL: process.env.EOS_TOKEN_SYMBOL,
    BLU_TOKEN_CONTRACT_BSC: process.env.BLU_TOKEN_CONTRACT_BSC,
    BLU_BRIDGER_CONTRACT_BSC: process.env.BLU_BRIDGER_CONTRACT_BSC,
  },
};
